### ISSUE TITLE
preloadData doesn't resolve when no data

### ISSUE THREAD

**Issue by laggingreflex** [overlookmotel/react-lazy-data#30] opened 2020-10-08 20:10 UTC
In normal mode, without SSR injecting the data from `extractor.getScript`, the `preloadData` method never resolves, I'm guessing since it never finds the data. 

Is there any way to conditionally tell that data won't be arriving, so resolve the promise immediately and hydrate/render?

**Comment by overlookmotel** [comment] 2020-10-11 21:06
Hi @laggingreflex.

Yes, that's the intended behavior. The package is designed so that `preloadData()` can be included in a script in the document's head, so it needs to wait for the data, and has no way of knowing when that'll be, so it'll wait forever if the data never comes.

Anyway, the page *can't* be hydrated without the data. The page has been rendered with the data on the server-side so it also needs the data on client side for hydration, or you'd end up rendering something different on the client, which would be a hydration mismatch. That'll create warnings from React and unexpected (buggy) behavior.

If you don't want data to be used for initial render on client, you can prevent it being used on server too with the `noSsr` option.

```js
const PokemonResource = createResourceFactory(
  id =>
    fetch(`https://pokeapi.co/api/v2/pokemon/${id}`)
      .then(res => res.json()),
  { noSsr: true }
);
```

The `noSsr` option isn't actually documented. I must have forgotten that. Sorry!

But you can read more about the background to this [here](https://www.npmjs.com/package/react-async-ssr#preventing-server-side-rendering-of-components).

Hopefully this provides a solution, so closing this issue. Shout me back if it doesn't.

**Closed as completed by overlookmotel** 2020-10-11 21:06 UTC

**Comment by laggingreflex** [comment] 2020-10-11 21:26
I'm using SSR in parallel with normal JS app. So sometimes (or some pages) will be server-rendered but other times not. That's when this become an issue. 

I guess I could just check the HTML with some markers and only preloadData when it hints at a server-rendered page.
